export const navLinks = [
  {
    label: "Services",
    href: "#",
    dropdown: [
      {
        categoryId: "mobile-app-development",
        category: "Mobile App Development",
        description: "Innovative, user-friendly mobile apps tailored to your business needs",
        items: [
          { label: "Mobile App Development", href: "#" },
          { label: "iOS App Development", href: "#" },
          { label: "Android App Development", href: "#" },
          { label: "Cross Platform App Development", href: "#" },
          { label: "Flutter App Development", href: "#" },
          { label: "React Native App Development", href: "#" },
          { label: "PWA Development", href: "#" },
          { label: "Wearable App Development", href: "#" },
          { label: "Mobile App Testing", href: "#" },
        ],
      },
      {
        categoryId: "software-development",
        category: "Software Development",
        description: "Custom software solutions designed for scalability and efficiency",
        items: [
          { label: "Enterprise Software Development", href: "#" },
          { label: "SaaS Development", href: "#" },
          { label: "CRM Software Development", href: "#" },
          { label: "Software Testing", href: "#" },
        ],
      },
      {
        categoryId: "web-development",
        category: "Web Development",
        description: "Robust, responsive, and high-performance websites for all industries",
        items: [
          { label: "PHP", href: "#" },
          { label: "Node.js", href: "#" },
          { label: "Python Web", href: "#" },
          { label: "CakePHP", href: "#" },
          { label: "MEAN Stack", href: "#" },
          { label: "Angular JS", href: "#" },
          { label: "CodeIgniter", href: "#" },
          { label: "Laravel", href: "#" },
          { label: "UI/UX Design", href: "#" },
        ],
      },
      {
        categoryId: "game-development",
        category: "Game Development",
        description: "Engaging and immersive gaming experiences with cutting-edge technology",
        items: [
          { label: "Mobile Game", href: "#" },
          { label: "Video Game", href: "#" },
          { label: "NFT Game", href: "#" },
          { label: "AR Game", href: "#" },
          { label: "Unity Game", href: "#" },
          { label: "iOS Game", href: "#" },
          { label: "Android Game", href: "#" },
          { label: "2D Game", href: "#" },
          { label: "3D Game", href: "#" },
          { label: "Casino Game", href: "#" },
          { label: "Ludo Game", href: "#" },
          { label: "HTML5 Game", href: "#" },
          { label: "Blockchain Game", href: "#" },
        ],
      },
      {
        categoryId: "digital-marketing",
        category: "Digital Marketing",
        description: "Data-driven strategies to enhance online visibility, engagement, and growth",
        items: [
          { label: "SEO", href: "#" },
          { label: "PPC", href: "#" },
          { label: "ORM", href: "#" },
          { label: "SMO", href: "#" },
          { label: "Facebook Marketing", href: "#" },
          { label: "LinkedIn Marketing", href: "#" },
          { label: "Email Marketing", href: "#" },
        ],
      },
      {
        categoryId: "on-demand-app-development",
        category: "On-Demand App Development",
        description: "Scalable on-demand solutions tailored for instant service delivery",
        items: [
          { label: "Appointment App Development", href: "#" },
          { label: "Booking System Development", href: "#" },
          { label: "On-Demand Delivery App Development", href: "#" },
        ],
      },
      {
        categoryId: "ai-development",
        category: "AI Development",
        description: "Advanced AI solutions driving automation, insights, and efficiency",
        items: [
          { label: "Generative AI Development", href: "#" },
          { label: "AI Chatbot Development", href: "#" },
          { label: "AI Consulting", href: "#" },
          { label: "AI Recommendation Engine Development", href: "#" },
          { label: "AI Agent Development", href: "#" },
          { label: "ML Development", href: "#" },
          { label: "Computer Vision Software Development", href: "#" },
          { label: "Agentic AI Development", href: "#" },
          { label: "Enterprise AI Development", href: "#" },
        ],
      },
      {
        categoryId: "e-commerce-development",
        category: "E-commerce Development",
        description: "Custom eCommerce platforms designed for seamless shopping experiences",
        items: [
          { label: "E-commerce Website Development", href: "#" },
          { label: "E-commerce App Development", href: "#" },
          { label: "Magento E-commerce Development", href: "#" },
          { label: "Shopify Development Services", href: "#" },
        ],
      },
      {
        categoryId: "product-engineering",
        category: "Product Engineering",
        description: "End-to-end product development from ideation to market success",
        items: [
          { label: "Product Engineering", href: "#" },
        ],
      },
    ],
  },
  {
    label: "Industries",
    href: "#",
    dropdown: [
      {
        categoryId: "logistics",
        category: "Logistics",
        description: "Streamline supply chain with custom logistics software solutions",
        items: [
          { label: "Logistics App Development", href: "#" },
          { label: "Warehouse Management", href: "#" },
          { label: "Supply Chain Software Development", href: "#" },
          { label: "Supply Chain Planning Software Development", href: "#" },
          { label: "Inventory Management", href: "#" },
          { label: "Fleet Management", href: "#" },
        ],
      },
      {
        categoryId: "healthcare",
        category: "Healthcare",
        description: "Build secure, scalable healthcare software for better patient care",
        items: [
          { label: "Custom Healthcare Software Development", href: "#" },
          { label: "Healthcare App Development", href: "#" },
          { label: "Doctor Appointment App Development", href: "#" },
          { label: "Fitness App Development Company", href: "#" },
        ],
      },
      {
        categoryId: "real-estate",
        category: "Real Estate",
        description: "Build a cutting edge real estate apps for seamless property buying and selling",
        items: [
          { label: "Real Estate App Development", href: "#" },
        ],
      },
      {
        categoryId: "travel-hospitality",
        category: "Travel & Hospitality",
        description: "Launch smart travel apps for seamless booking and trip planning",
        items: [
          { label: "Travel App Development", href: "#" },
          { label: "Hotel App Development", href: "#" },
        ],
      },
      {
        categoryId: "education",
        category: "Education",
        description: "Develop interactive eLearning apps to enhance digital education experiences",
        items: [
          { label: "Education App Development", href: "#" },
          { label: "eLearning Software Development", href: "#" },
        ],
      },
      {
        categoryId: "on-demand",
        category: "On-Demand",
        description: "Custom on-demand apps to connect users with instant services",
        items: [
          { label: "Taxi App Development", href: "#" },
          { label: "Food Delivery App Development", href: "#" },
          { label: "Grocery Delivery App Development", href: "#" },
          { label: "Live Streaming App Development", href: "#" },
          { label: "Doctor Appointment App Development", href: "#" },
          { label: "Car Wash App Development", href: "#" },
          { label: "Beauty Salon App Development", href: "#" },
          { label: "Restaurant App Development", href: "#" },
          { label: "Hotel Booking App Development", href: "#" },
          { label: "Class Scheduling Software", href: "#" },
          { label: "Meeting Room Booking System", href: "#" },
          { label: "Ticket Booking App Development", href: "#" },
          { label: "Event Management App Development", href: "#" },
          { label: "Milk Delivery App Development", href: "#" },
          { label: "Fuel Delivery App Development", href: "#" },
        ],
      },
      {
        categoryId: "media-entertainment",
        category: "Media & Entertainment",
        description: "We dive into the entertainment industry to bring some great app ideas to life.",
        items: [
          { label: "Social Media App Development Company", href: "#" },
          { label: "Video Streaming App Development", href: "#" },
          { label: "Roku TV App Development", href: "#" },
          { label: "Smart TV App Development", href: "#" },
          { label: "Music Streaming App Development", href: "#" },
          { label: "Entertainment App Development", href: "#" },
          { label: "OTT App Development", href: "#" },
        ],
      },
    ],
  },
  {
    label: "Resources",
    href: "#",
  },
  {
    label: "Company",
    href: "#",
    dropdown: [
      {
        categoryId: "about-us",
        category: "About Us",
        description: "Learn about our app and software development services that help businesses grow and succeed",
        items: [{ label: "About Us", href: "#" }],
      },
      {
        categoryId: "case-studies",
        category: "Case Studies",
        description: "Explore our successful projects and innovative solutions that solve real-world challenges",
        items: [{ label: "Case Studies", href: "#" }],
      },
      {
        categoryId: "career",
        category: "Career",
        description: "Join our team to develop your skills and work in a dynamic environment",
        items: [{ label: "Career", href: "#" }],
      },
      {
        categoryId: "infrastructure",
        category: "Infrastructure",
        description: "Experience cutting-edge technology and a strong development setup that ensures efficiency and security",
        items: [{ label: "Infrastructure", href: "#" }],
      },
      {
        categoryId: "testimonials",
        category: "Testimonials",
        description: "Read what our clients say about our services and how we have helped their businesses",
        items: [{ label: "Testimonials", href: "#" }],
      },
      {
        categoryId: "referral-partner-program",
        category: "Referral Partner Program",
        description: "Partner with us to refer clients, earn exciting rewards, and grow your network",
        items: [{ label: "Referral Partner Program", href: "#" }],
      },
      {
        categoryId: "news",
        category: "News",
        description: "Stay informed about our latest achievements, industry trends, technology updates, innovations, and success stories",
        items: [{ label: "News", href: "#" }],
      },
      {
        categoryId: "portfolio",
        category: "Portfolio",
        description: "Discover our top app and software projects that bring ideas to life with creativity and expertise",
        items: [{ label: "Portfolio", href: "#" }],
      },
    ],
  },
];